In [50]:
import pandas as pd 
from sklearn.model_selection import train_test_split
import lazypredict 
from lazypredict.Supervised import LazyRegressor

In [51]:
# Definimos la semilla
SEMILLA = 42

In [52]:
# Lectura del dataset
data = pd.read_csv('properati_caba_2021.csv')

In [53]:
# Observamos los primeros registros del dataframe
data.head()

,id,lat,lon,l3,rooms,bathrooms,surface_total,surface_covered,price,property_type
0,5dmWZ4uqAU4kpJw0AEc/Hw==,-34.62,-58.40,San Cristobal,7.00,6.00,534.00,384.00,470000.00,Casa
1,kFa6ndbLuJ2k2zfzI1fY3A==,-34.56,-58.46,Belgrano,1.00,1.00,25.00,25.00,60000.00,Departamento
2,S0fct9jgpfmuqmOaPntC/Q==,-34.62,-58.38,Monserrat,1.00,1.00,40.00,40.00,82500.00,Departamento
3,sduUfHxdOh9PuRwJruEcyA==,-34.62,-58.38,San Telmo,1.00,1.00,40.00,40.00,82500.00,Departamento
4,Tl1ebIQJyPOXV2XJMEImQg==,-34.62,-58.38,Constitución,1.00,1.00,40.00,40.00,82500.00,Departamento

In [54]:
# Observamos la matriz de correlación entre las variables numéricas
data.corr()

,lat,lon,rooms,bathrooms,surface_total,surface_covered,price
lat,1.00,-0.14,-0.01,0.10,0.02,0.04,0.15
lon,-0.14,1.00,0.05,0.08,0.05,0.09,0.18
rooms,-0.01,0.05,1.00,0.62,0.74,0.75,0.49
bathrooms,0.10,0.08,0.62,1.00,0.74,0.75,0.67
surface_total,0.02,0.05,0.74,0.74,1.00,0.97,0.72
surface_covered,0.04,0.09,0.75,0.75,0.97,1.00,0.76
price,0.15,0.18,0.49,0.67,0.72,0.76,1.00

In [55]:
# Separamos al dataset en X (variables predictoras) e y (variable a predecir)
X = df[[ 'rooms', 'bathrooms', 'surface_total', 'surface_covered']]
y = df['price']

In [56]:
from sklearn.model_selection import train_test_split
# Realizamos el split de X e y en los sets de entrenamiento (train) y test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=SEMILLA)

In [57]:
# Para tareas de regresión
reg = LazyRegressor(verbose=0, ignore_warnings=True, predictions=True, random_state =  SEMILLA)
models, predictions = reg.fit(X_train, X_test, y_train, y_test)

100%|██████████| 42/42 [06:42<00:00,  9.58s/it]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000606 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 541
[LightGBM] [Info] Number of data points in the train set: 32124, number of used features: 4
[LightGBM] [Info] Start training from score 245499.655491

In [58]:
models.head(15)

,Adjusted R-Squared,R-Squared,RMSE,Time Taken
Model,,,,
RandomForestRegressor,0.65,0.65,197526.48,4.60
LassoLarsCV,0.64,0.64,199850.17,0.05
LarsCV,0.64,0.64,199850.17,0.11
OrthogonalMatchingPursuitCV,0.64,0.64,199850.17,0.03
LassoLarsIC,0.64,0.64,199850.17,0.06
Lars,0.64,0.64,199850.17,0.23
TransformedTargetRegressor,0.64,0.64,199850.17,0.03
LinearRegression,0.64,0.64,199850.17,0.04
LassoLars,0.64,0.64,199850.94,0.03
Lasso,0.64,0.64,199850.95,0.03
Ridge,0.64,0.64,199854.96,0.02
BayesianRidge,0.64,0.64,199859.18,0.05
GradientBoostingRegressor,0.64,0.64,199883.02,1.30
RidgeCV,0.64,0.64,199898.04,0.03
LassoCV,0.64,0.64,200042.25,0.31

In [59]:
predictions.head()

,AdaBoostRegressor,BaggingRegressor,BayesianRidge,DecisionTreeRegressor,DummyRegressor,ElasticNet,ElasticNetCV,ExtraTreeRegressor,ExtraTreesRegressor,GammaRegressor,...,RANSACRegressor,RandomForestRegressor,Ridge,RidgeCV,SGDRegressor,SVR,TransformedTargetRegressor,TweedieRegressor,XGBRegressor,LGBMRegressor
0,228968.84,214928.57,180022.93,207747.48,245499.66,191236.47,244862.47,207747.48,207747.48,174113.15,...,180061.19,209371.87,180038.49,179881.35,180233.31,154946.08,180056.17,202048.48,188592.42,188580.82
1,294374.96,273537.08,320488.60,220725.00,245499.66,329842.74,247122.24,299000.00,265603.50,250171.98,...,250576.81,252777.32,320494.04,320439.26,306135.61,161310.78,320500.23,325697.63,318698.81,298953.89
2,112564.81,94430.07,100085.44,94290.30,245499.66,114400.22,243411.69,94290.30,94290.30,139537.87,...,109747.86,94360.00,100091.05,100034.46,106628.80,150499.26,100097.42,129835.00,97081.09,100720.71
3,744567.56,242700.00,515875.50,130000.00,245499.66,548703.57,250178.81,630000.00,289404.00,394957.25,...,448760.09,367419.26,515773.57,516804.31,496984.95,160433.09,515657.77,510097.69,372152.19,428587.70
4,112564.81,137013.53,120031.06,139345.56,245499.66,132591.67,243663.21,139345.56,139345.56,144895.42,...,125485.36,138948.17,120031.38,120028.17,126168.38,150863.50,120031.75,145090.58,134329.66,128959.05